Develop
AndreyBMWX6/raft-db pull request #2
Opened 2020-10-14 19:55 UTC by AndreyBMWX6

2020-11-12 17:39 UTC, AndreevSemen requested changes
Накидал свои мысли, если есть спорные моменты или я что-то пропустил, то говори

2020-11-12 17:39 UTC, AndreevSemen commented on cmd/main.go
> +	}
Надо будет это все брать из кофигфайла (адреса, порты и тд). Нужно будет конфигурацию замутить

2020-11-12 17:39 UTC, AndreevSemen commented on cmd/main.go
> +	}
Также нужно будет сделать helper-функцию (NewRaftCore) для того, чтобы создавать кору (использую при этом конфиг, а не захардкоженые значения типа `neighbors`)

2020-11-12 17:39 UTC, AndreevSemen commented on internal/config/config.go
> +}
Перенеси захардкоженые значения из замечания из `main.go` сюда для начала

2020-11-12 17:39 UTC, AndreevSemen commented on internal/manager/client_manager.go
> +}
Добавь перенос на новую строчку

2020-11-12 17:39 UTC, AndreevSemen commented on internal/manager/raft_manager.go
> +func (rm *RaftManager) RaftManagerProcessMessage() {
Зачем в имени `RaftManager`, если это и так метод структуры  `RaftManager`?

2020-11-12 17:39 UTC, AndreevSemen commented on internal/manager/raft_manager.go
> +	}
Почему 2 раза занимается адрес `127.0.0.1:800` (см. `main.go`)
Лучше занимать адрес тут, в менеджере. Сам адрес, в свою очередь, нужно брать из конфига

2020-11-12 17:39 UTC, AndreevSemen commented on internal/manager/raft_manager.go
> +	}
Прошу прощения, получилась путаница, потому что адрес берется не из конфга, а два раза резолвится в разных местах >:(

Но все равно совет из верхнего действителен

2020-11-12 17:39 UTC, AndreevSemen commented on internal/manager/raft_manager.go
> +			var Destport = uint32(msg.DestAddr().Port)
Во-первый, почему где-то:
```go
name := val
```
А в другом месте так:
```go
var name = val
```

Во-вторых, в го принят `camelCase`

2020-11-12 17:39 UTC, AndreevSemen commented on internal/manager/raft_manager.go
> +			baseraftmessage.CurrTerm = msg.Term()
Нужна функция `GetBaseMessage(raftMsg) -> *net_messages.BaseRaftMessage`

2020-11-12 17:39 UTC, AndreevSemen commented on internal/manager/raft_manager.go
> +func (rm *RaftManager) RaftManagerProcessMessage() {
Из названия не понятно в какую сторону идет обработка сообщения, то ли мы отправляем это в сеть, то ли принимаем, то ли делаем и то, и то

2020-11-12 17:39 UTC, AndreevSemen commented on internal/manager/raft_manager.go
> +				}
Нужна функция отправки по сети готового сообщения сообщения (тип сообщения нужно просто аргументом передать)

2020-11-12 17:39 UTC, AndreevSemen commented on internal/manager/raft_manager.go
> +				data := &net_messages.AppendEntries{}
Зачем создавать новую переменную, если можно преобразовать `raftmessage` в нужный нам тип (в `raftmessage` даже все поля заполнены уже)

2020-11-12 17:39 UTC, AndreevSemen commented on internal/manager/raft_manager.go
> +				data := &net_messages.RequestVote{}
см. выше

2020-11-12 17:39 UTC, AndreevSemen commented on internal/manager/raft_manager.go
> +				}
см. выше

2020-11-12 17:39 UTC, AndreevSemen commented on internal/manager/raft_manager.go
> +				}
см. выше

2020-11-12 17:39 UTC, AndreevSemen commented on internal/manager/raft_manager.go
> +				}
см. выше

2020-11-12 17:39 UTC, AndreevSemen commented on internal/manager/raft_manager.go
> +		default:
Поговорили с тобой уже, вынеси это в отдельную горутину

2020-11-12 17:39 UTC, AndreevSemen commented on internal/manager/raft_manager.go
> +						Destip := net.IPv4(
`camelCase`

2020-11-12 17:39 UTC, AndreevSemen commented on internal/manager/raft_manager.go
> +					}
Можно попробовать вынести этот функционал ближе к реализациям типов `Raft`-сообщений

2020-11-12 17:39 UTC, AndreevSemen commented on internal/manager/raft_manager.go
> +					}
см. выше (и так для всех анмаршелов)

2020-11-12 17:39 UTC, AndreevSemen commented on internal/manager/raft_manager.go
> +}
Новую строку добавь

2020-11-12 17:39 UTC, AndreevSemen commented on internal/node/candidate_chatting.go
> +			fmt.Print("candidate:")
Что это значит, может ты забыл что-то дописать?

2020-11-12 17:39 UTC, AndreevSemen commented on internal/node/candidate_chatting.go
> +			fmt.Print("candidate:")
Кстати, что думаешь насчет того, чтобы для пущей наглядности выводить что-то типа:
```
[follower  -> candidate]
[candidate -> follower ]
[follower  -> candidate]
[candidate -> leader   ]
[leader    -> folower  ]
```

2020-11-12 17:39 UTC, AndreevSemen commented on internal/tests/candidate_test.go
> +func TestApplyRaftMessage(t *testing.T) {
За тесты лайк, но нужно еще добавить тестов, маловато для такого кода

2020-11-12 17:44 UTC, AndreyBMWX6 commented on cmd/main.go
> +	}
и ещё тогда надо будет сделать helper-функциb NewFollower и NewLeader, чтобы можно было начинать работу с разных состояний

2020-11-12 17:52 UTC, AndreyBMWX6 commented on internal/tests/candidate_test.go
> +func TestApplyRaftMessage(t *testing.T) {
нужно их ещё переделать)))

2020-11-12 17:58 UTC, AndreyBMWX6 commented on internal/node/candidate_chatting.go
> +			fmt.Print("candidate:")
нет, не забыл, это комментарий к нижней строке, чтобы потом было проще найти и удалить, когда буду переделывать. Про наглядность отличная идея!

2020-11-16 07:39 UTC, AndreevSemen requested changes

2020-11-16 07:39 UTC, AndreevSemen commented on internal/config/config.go
> +	}
Хмм, а тут мы резолвим уже адрес, можно ли сделать так, чтобы мы его больше никогда не резолвили еще раз?

2020-11-16 07:39 UTC, AndreevSemen commented on internal/manager/client_manager.go
> +package manager
Этот код никак не относится к проекту, зачем он попал в его историю?

2020-11-16 07:39 UTC, AndreevSemen commented on internal/message/request_vote.go
> +}
Перенос строки

2020-11-16 07:57 UTC, AndreevSemen reviewed
Обозначил из-за чего могут быть проблемы, попробуй

2020-11-16 07:57 UTC, AndreevSemen commented on internal/node/node.go
> +func (n *RaftCore) TryRecvRaftMsg(raftMsg message.RaftMessage) {
Почему функция ничего не возвращает? Разве она не должна возвращать `message.RaftMessage`?

2020-11-16 07:57 UTC, AndreevSemen commented on internal/node/node.go
> +	}
Почему у мультиплексора нет блока `default`? Мне кажется, что функция `TryRecvRaftMsg` не обязана ждать получения сообщения из канала. Но при отсутствии блока `default` функция не закончит работу без получения чего-либо из канала

2020-12-15 10:00 UTC, AndreevSemen requested changes

2020-12-15 10:00 UTC, AndreevSemen commented on README.md
> +cd "<"path to your raft-db folder">/cmd"
Сделай вот так:

Paths are set this way:
```bash
cd "<"path to your raft-db folder">/cmd"
```

2020-12-15 10:00 UTC, AndreevSemen commented on README.md
> +$ script.bat
Здесь тоже оформь в том же стиле

2020-12-15 10:00 UTC, AndreevSemen commented on cmd/main.go
> +		node.RunRolePlayer(candidate)
Много повторяющегося кода. Можно объединить примерно в такую структуру:
```go
var raftNode *node.RaftCore
if *runAll {
    ip := flag.Arg(0)
    if ip == "" {
        log.Println("Error: no ip")
    }
    ipPort := flag.Arg(1)
    if ipPort == "" {
        log.Println("Error: no port")
    }
    urlPort := flag.Arg(2)
    if urlPort == "" {
        log.Println("Error: no URL port")
    }
    runRouter := flag.Arg(3)
    if runRouter == "" {
        log.Println("Error: no router info")
    }
    username := flag.Arg(4)
    if urlPort == "" {
        log.Println("Error: no username")
    }

    raftNode = node.NewAllRunRaftCore(ip, ipPort, urlPort)
} else {
    raftNode = node.NewRaftCore()
}

var candidate = node.NewCandidate(raftNode)

rm := &manager.RaftManager{
    RaftIn  : raftNode.RaftOut,
    RaftOut : raftNode.RaftIn,
    Addr    : raftNode.Config.Addr,
}

cm := &manager.ClientManager{
    ClientIn  : raftNode.ClientOut,
    ClientOut : raftNode.ClientIn,
    UrlPort   : raftNode.URL[len(raftNode.URL) - 4:],
}

dbm := &manager.MongoDBManager{
    DBIn     : raftNode.DBOut,
    DBOut    : raftNode.DBIn,
    Username : raftNode.Config.Username,
}

r := router.NewRouter()
go rm.ProcessMessage()
go cm.ProcessEntries()
go dbm.ProcessMessage()
go r.RunRouter()

node.RunRolePlayer(candidate)
```

2020-12-15 10:00 UTC, AndreevSemen commented on cmd/main.go
> +			log.Println("Error: no ip")
Если появилась такая ошибка, то скорее всего стоит зафаталить прогу:
```go
log.Fatalf("Error: no ip")
```

2020-12-15 10:00 UTC, AndreevSemen commented on cmd/main.go
> +			log.Println("Error: no port")
same shit

2020-12-22 17:43 UTC, merged